### ISSUE TITLE
Not working as turbosound

### ISSUE THREAD

**Issue by kazmat6502** [konkotgit/KTS#1]
Hi
I made 2pcs KTS, but  2nd AY not recognize using AYtest_v0.2.tap.

What's wrong ?

**Comment by konkotgit** [comment]
Hi

What computer are you using with this interface?

niedz., 26 wrz 2021 o 13:00 kazmat6502 ***@***.***>
napisał(a):

**Comment by kazmat6502** [comment]
Sizif-512 and Karabas-128

**Comment by konkotgit** [comment]
Try to remove internal AY and test again.

niedz., 26 wrz 2021, 13:37 użytkownik kazmat6502 ***@***.***>
napisał:

**Comment by kazmat6502** [comment]
Oh! working as turbosound !!! Thank you.
Keep up good work !!!

**Comment by konkotgit** [comment]
Great. I need to update description on project page.

niedz., 26 wrz 2021, 14:47 użytkownik kazmat6502 ***@***.***>
napisał:
